### ISSUE TITLE
npm WARN cannot run in wd ghost@0.10.1 node core/server/utils/npm/preinstall.js (wd=/srv/ghost)

### ISSUE THREAD

**Issue by MeowCold** [evil7/AutoGhost.sh#1]
npm WARN cannot run in wd ghost@0.10.1 node core/server/utils/npm/preinstall.js (wd=/srv/ghost)

**Comment by evil7** [comment]
Maybe U should update your nodejs ver to v4.
In this script I already used v4 to build the blog. U can uninstall your nodejs and run this script.
Or run this in a debian or ubuntu. pureness OS. new install OS. like reinstall VPS.
And I'm so sorry I can't update this on time. many dayshift and to much work to do.

This is some Info useful. I think that should be check:
[https://dev.ghost.org/node-4/](https://dev.ghost.org/node-4/)
[https://github.com/nodejs/LTS](https://github.com/nodejs/LTS)
[https://github.com/TryGhost/Ghost/issues/7098](https://github.com/TryGhost/Ghost/issues/7098)

**Comment by MeowCold** [comment]
[error.log.txt](https://github.com/evil7/AutoGhost.sh/files/471563/error.log.txt)不知道怎么回事 纯净系统安装后提示502
系统：Ubuntu 16.04.1 LTS
服务商：Azure国际（东亚）

**Comment by evil7** [comment]
不知道你那是nodejs没跑起来还是nginx的问题。刚我这边测试环境重装了一遍，是能够执行的。
你可以`curl 127.0.0.1:2368` 看看nodejs跑起来没有。如果没有，可能是nodejs的问题，你可以手动一步步安装试试，如果是nginx的问题可能是配置原因，去修改conf试试吧。

**Comment by MeowCold** [comment]
curl: (7) Failed to connect to 127.0.0.1 port 2368: Connection refused

**Comment by evil7** [comment]
试试用ubuntu15试试，16有很多系统组建更新了，可能有某些安装的插件不适配。可能是nodejs的某些依赖在16下的问题吧。我的用的ubuntu14。因为生产环境太高容易出现依赖跟不上系统更新。

**Comment by MeowCold** [comment]
已换为：
系统：Ubuntu 14.04 LTS

root@YB:/srv/ghost# npm start

> ghost@0.10.1 start /srv/ghost
> node index

WARNING: Ghost is attempting to use a direct method to send email. 
It is recommended that you explicitly configure an email service.
Help and documentation can be found at http://support.ghost.org/mail.

Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/srv/ghost/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/srv/ghost/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Client._driver (/srv/ghost/node_modules/knex/lib/dialects/sqlite3/index.js:37:12)
    at Client.initializeDriver (/srv/ghost/node_modules/knex/lib/client.js:162:26)
    at Client (/srv/ghost/node_modules/knex/lib/client.js:41:10)
    at Client_SQLite3 (/srv/ghost/node_modules/knex/lib/dialects/sqlite3/index.js:23:10)
    at new Client (/srv/ghost/node_modules/knex/lib/util/make-client.js:15:18)
    at Knex (/srv/ghost/node_modules/knex/lib/index.js:26:19)
    at Object.<anonymous> (/srv/ghost/core/server/data/db/connection.js:54:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.get [as knex] (/srv/ghost/core/server/data/db/index.js:7:36)
    at Object.<anonymous> (/srv/ghost/core/server/models/base/index.js:29:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.init (/srv/ghost/core/server/models/index.js:35:20)
    at /srv/ghost/core/server/index.js:67:16

**Comment by MeowCold** [comment]
是否最后添加一个检测 检测环境缺什么

**Comment by MeowCold** [comment]
能否最后检测 是否缺失环境所需 
发现最后在/srv/ghost 执行
npm install sqlite3 --build-from-source
npm start
提示正常了

**Comment by 1214238229** [comment]
##### 不至于吧

我也是这个问题，以前装的ghost好好地，然后更新了一下ghost就出现这个问题

**绝对不可能**是系统的问题

估计是ghost哪里设置的不正确或者什么服务啥的没关闭
